<?php
// Get the block instance
$block = $this->getLayout()->getBlock('HellosWorld');

// Access the customer session
$customerSession = $block->getCustomerSession();
// Fetch and display the blog collection
$blogCollection = $block->getHelloCollection();

// Check if the customer is logged in
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getCustomerId();
    $customer = $customerSession->getCustomer();
    $customerName = $customer->getName();

    echo '<p>Logged in customer ID: ' . $customerId . '</p>';
    echo '<p>Customer Name is : ' . $customerName . '</p>';

    if (count($blogCollection)) {
        foreach ($blogCollection as $blog) {
            $postUrl = $this->getUrl('helloworld/post/view', ['id' => $blog->getId()]);
            echo '<h2><a href="' . $postUrl . '">' . $blog->getTitle() . '</a></h2><br />';
        }
    } else {
        echo '<p>No posts found for this account.</p>';
    }
} else {
    echo '<p>Customer is not logged in.</p>';
}

// Display the pager if available
if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom">
        <?php echo $block->getPagerHtml(); ?>
    </div>
<?php endif; ?>
