<?php
/**
 * Template for displaying restricted countries
 */

echo 'hihihihooooooooooooo';

//$block = $this->getLayout()->getBlock('restrictedcountries');
//
//$restrictedCountries = $block->getRestrictedCountries();
//
//if ($restrictedCountries) {
//    echo '<div class="restricted-countries">';
//    echo '<strong>Restricted Countries:</strong> ' . $block->escapeHtml($restrictedCountries);
//    echo '</div>';
//}
//else{
//    echo 'Nothing found';
//}
?>
